# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/NN.POS.API" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget" # See documentation for possible values
      directory: "/NN.POS.Common" # Location of package manifests
      schedule:
        interval: "weekly"
        day: "wednesday"
      open-pull-requests-limit: 5
  - package-ecosystem: "nuget" # See documentation for possible values
      directory: "/NN.POS.Model" # Location of package manifests
      schedule:
        interval: "weekly"
        day: "wednesday"
      open-pull-requests-limit: 5
  - package-ecosystem: "nuget" # See documentation for possible values
      directory: "/NN.POS.Web" # Location of package manifests
      schedule:
        interval: "weekly"
        day: "wednesday"
      open-pull-requests-limit: 5
